export const userData =[
    {
      id: 'Jainika',
      username: "Jainika",
      password: "123456",
      userType: 'Admin',
      number: 1234432221,
      email: "j@g.com",
      state: "Gujarat",
      // createdAt: new Date(),
      createdAt : new Date(),
      updatedAt: null,
      country: "India",
      gender: "female",
      status:'Active'
    },
    {
      id: 'Niyosh',
      username: "Niyosh",
      password: "1222456",
      userType: 'FE Trainee',
      number: 1234432221,
      email: "n@g.com",
      state: "Gujarat",
      // createdAt: new Date(),
      createdAt : new Date(),
      updatedAt: 'Nov 19, 2021, 04:11 PM',
      country: "India",
      gender: "female",
      status:'Inactive'
    
    },
    {
        id: 'Nidhi',
        username: "Nidhi",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "nidhi@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
      createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Active'
      },
      {
        id: 'Siddhi',
        username: "Siddhi",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "siddhi@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Inactive'
      },
      {
        id: 'Vanshika',
        username: "Vanshika",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "vanshika@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Inactive'
      },
      {
        id: 'Sanya',
        username: "Sanya",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "sanya@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Active'
      },
      {
        id: 'Yashvi',
        username: "Yashvi",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "yashvi@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Active'
      },
      {
        id: 'Aachal',
        username: "Aachal",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "aachal@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Inactive'
      },
      {
        id: 'Rishabh',
        username: "Rishabh",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "rishabh@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "male",
        status:'Active'
      },
      {
        id: 'Yash',
        username: "Yash",
        password: "122246",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "yash@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "male",
        status:'Inactive'
      },
      {
        id: 'Krishna',
        username: "Krishna",
        password: "1222456",
        userType: 'FE Trainee',
        number: 1234432221,
        email: "krishna@g.com",
        state: "Gujarat",
        // createdAt: 'Nov 18, 2021, 06:48 PM',
        createdAt : new Date(),
        updatedAt: 'Nov 19, 2021, 04:11 PM',
        country: "India",
        gender: "female",
        status:'Inactive'
      },

  ]